# Change these first
owner: SSRQ-SDS-FDS # Your GitHub organization or username, where this repository lives
repo: ssrq-uptime # The name of this repository
assignees: # Users to assign downtime issues (optional)
  - Bpolitycki
  - ChristianSonderUniSG
sites:
  - name: SSRQ Project Website
    url: http://ssrq-sds-fds.ch
  - name: Editio – the digital scholarly edition
    url: https://editio.ssrq-online.ch
  - name: IIIF Server
    url: https://facsimiles.ssrq-sds-fds.ch/iiif/2/ADCO_BII_8_19_1r.ptif/info.json
  - name: Schema
    url: https://schema.ssrq-sds-fds.ch/latest/
  - name: SSRQ PersonsDB
    url: https://personae.ssrq-sds-fds.ch
  - name: SSRQ PlacesDB
    url: https://loci.ssrq-sds-fds.ch/search/search-form.xq
  - name: SSRQ LemmaDB
    url: https://termini.ssrq-sds-fds.ch/search/search-form.xq
  - name: Resolver for permanent links
    url: https://p.ssrq-sds-fds.ch/loc123456
    expectedStatusCodes:
      - 200
      - 301

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.ssrq-sds-fds.ch
  #baseUrl: /your-repo-name
  logoUrl: https://github.com/SSRQ-SDS-FDS/ssrq-uptime/blob/0cc813ac056da82664641648779ffb11dace6de8/assets/SSRQ-2020-512.png?raw=true
  name: SSRQ Service Monitoring
  introTitle: "SSRQ Services – Status"
  introMessage: Simple Status Monitoring powered by [Upptime](https://upptime.js.org)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
